[package]
name = "cable"
version = "0.1.0"
authors = ["Volhorc <69816212+Ocrrcc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
